<template>
  <Tree :data="data4" show-checkbox multiple @on-check-change="aa"></Tree>
  <Table border :columns="columns7" :data="data6"></Table>
</template>
<script setup lang="ts">
import { getCurrentInstance, reactive, ref, resolveComponent } from "vue";
let data4 = ref([
  {
    resourceId: "MD11000000000000000002",
    resourceType: "0",
    resourceSourceId: null,
    resourceUri: "platform.identity",
    resourceUrl: null,
    resourceDescribe: null,
    parentResourceUri: null,
    title: "账户管理",
    expand: false,
    checked: false,
    disabled: false,
    path: null,
    name: null,
    icon: null,
    children: [
      {
        resourceId: "MD10MD0010000000000043",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "platform.identity.settings",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "platform.identity",
        title: "账号管理",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [],
      },
    ],
  },
  {
    resourceId: "MD11000000000000000008",
    resourceType: "0",
    resourceSourceId: null,
    resourceUri: "arapc.appadmin",
    resourceUrl: null,
    resourceDescribe: null,
    parentResourceUri: null,
    title: "收付云后台管理",
    expand: false,
    checked: false,
    // disabled: false,
    path: null,
    name: null,
    icon: null,
    children: [
      {
        resourceId: "MD10A00030000000000063",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "arapc.appadmin.assomgr",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "arapc.appadmin",
        title: "会员管理",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10A00030000000000064",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.assomgr.assoAuthList",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.assomgr",
            title: "会员认证管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10A00030000000000065",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.assomgr.loginLock",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.assomgr",
            title: "账号锁定管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10A00030000000000074",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.assomgr.assoList",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.assomgr",
            title: "会员密码管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10A00030000000000088",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.assomgr.businessFunction",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.assomgr",
            title: "业务功能控制",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10A00030000000000089",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri:
                  "arapc.appadmin.assomgr.businessFunction.roleManage",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "arapc.appadmin.assomgr.businessFunction",
                title: "系统角色管理",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10A00030000000000090",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri:
                  "arapc.appadmin.assomgr.businessFunction.roleDistribute",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "arapc.appadmin.assomgr.businessFunction",
                title: "系统角色分配",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        resourceId: "MD10A00030000000000075",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "arapc.appadmin.billtx",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "arapc.appadmin",
        title: "票据交易",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10A00030000000000076",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.billtx.rate",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.billtx",
            title: "票据报价管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10A00030000000000077",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.billtx.finassistreq",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.billtx",
            title: "票据收单管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
        ],
      },
      {
        resourceId: "MD10A00030000000000078",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "arapc.appadmin.sysco",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "arapc.appadmin",
        title: "保理管理",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10A00030000000000079",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.sysco.commorg",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.sysco",
            title: "商圈保理维护",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10A00030000000000080",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.sysco.associator",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.sysco",
            title: "会员保理维护",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10A00030000000000081",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.sysco.supplier",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.sysco",
            title: "供应商保理维护",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
        ],
      },
      {
        resourceId: "MD10A00030000000000082",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "arapc.appadmin.corp",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "arapc.appadmin",
        title: "企业数据管理",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10A00030000000000083",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.corp.supplier",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.corp",
            title: "供应商档案管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10A00030000000000084",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.corp.supplierLogin",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.corp",
            title: "供应商账号管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
        ],
      },
      {
        resourceId: "MD10A00030000000000085",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "arapc.appadmin.cons",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "arapc.appadmin",
        title: "平台管理",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10A00030000000000086",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.cons.cousultRecord",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.cons",
            title: "咨询记录",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10A00030000000000087",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "arapc.appadmin.cons.accessLog",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "arapc.appadmin.cons",
            title: "访问记录",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    resourceId: "MD11000000000000000001",
    resourceType: "0",
    resourceSourceId: null,
    resourceUri: "platform.md",
    resourceUrl: null,
    resourceDescribe: null,
    parentResourceUri: null,
    title: "主数据管理",
    expand: false,
    checked: false,
    disabled: false,
    path: null,
    name: null,
    icon: null,
    children: [
      {
        resourceId: "MD10MD0010000000000001",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "platform.md.assomgr",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "platform.md",
        title: "会员管理",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10MD0010000000000002",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.assomgr.orgmgr",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.assomgr",
            title: "组织管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000005",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.orgmgr.org",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.orgmgr",
                title: "组织定义",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000006",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.orgmgr.orgType",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.orgmgr",
                title: "组织类型",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000007",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.orgmgr.orgMemberType",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.orgmgr",
                title: "组织成员类型",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000008",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.orgmgr.orgMember",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.orgmgr",
                title: "组织成员",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000009",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.orgmgr.orgOperator",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.orgmgr",
                title: "组织业务员",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000045",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.orgmgr.orgQry",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.orgmgr",
                title: "组织查询",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000046",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.orgmgr.orgTypeQry",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.orgmgr",
                title: "组织类型查询",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
          {
            resourceId: "MD10MD0010000000000003",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.assomgr.asso",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.assomgr",
            title: "会员维护",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000011",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.asso.assoAuthList",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.asso",
                title: "会员认证管理",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000012",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.asso.associator",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.asso",
                title: "会员档案管理",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
          {
            resourceId: "MD10MD0010000000000004",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.assomgr.usermgr",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.assomgr",
            title: "用户管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000014",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.usermgr.user",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.usermgr",
                title: "用户管理",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000042",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.usermgr.loginLock",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.usermgr",
                title: "账号锁定管理",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
          {
            resourceId: "MD10MD0010000000000044",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.assomgr.myasso",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.assomgr",
            title: "我的会员",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000010",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.myasso.assoAuthApply",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.myasso",
                title: "会员认证申请",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000013",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.assomgr.myasso.assoDetail",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.assomgr.myasso",
                title: "会员档案信息",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        resourceId: "MD10MD0010000000000015",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "platform.md.system",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "platform.md",
        title: "系统管理",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10MD0010000000000016",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.system.product",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.system",
            title: "产品管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10MD0010000000000017",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.system.module",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.system",
            title: "模块管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10MD0010000000000018",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.system.function",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.system",
            title: "功能管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
        ],
      },
      {
        resourceId: "MD10MD0010000000000019",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "platform.md.permission",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "platform.md",
        title: "权限管理",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10MD0010000000000020",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.permission.sysRole",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.permission",
            title: "系统角色管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000026",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.permission.sysRole.list",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.sysRole",
                title: "系统角色列表",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000027",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.permission.sysRole.authority",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.sysRole",
                title: "默认角色设置",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000038",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.permission.sysRole.authForAsso",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.sysRole",
                title: "系统角色授权",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
          {
            resourceId: "MD10MD0010000000000021",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.permission.role",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.permission",
            title: "角色权限",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000028",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.permission.role.list",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.role",
                title: "角色管理",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000029",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.permission.role.roleAssignedUser",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.role",
                title: "分配用户",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000030",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.permission.role.authority",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.role",
                title: "分配权限",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
          {
            resourceId: "MD10MD0010000000000022",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.permission.user",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.permission",
            title: "用户权限",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000031",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.permission.user.userAssignedRole",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.user",
                title: "分配角色",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
              {
                resourceId: "MD10MD0010000000000032",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.permission.user.authority",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.user",
                title: "分配权限",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
          {
            resourceId: "MD10MD0010000000000023",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.permission.finalAuthority",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.permission",
            title: "用户最终权限",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000033",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri:
                  "platform.md.permission.finalAuthority.listForPages",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.permission.finalAuthority",
                title: "权限查看",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
          {
            resourceId: "MD10MD0010000000000024",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.permission.resource",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.permission",
            title: "资源管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10MD0010000000000025",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.permission.action",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.permission",
            title: "操作管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
        ],
      },
      {
        resourceId: "MD10MD0010000000000034",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "platform.md.config",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "platform.md",
        title: "配置参数",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10MD0010000000000035",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.config.sysParameter",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.config",
            title: "系统参数",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10MD0010000000000036",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.config.assoParameter",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.config",
            title: "会员参数",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
          {
            resourceId: "MD10MD0010000000000037",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.config.userParameter",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.config",
            title: "用户参数",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [],
          },
        ],
      },
      {
        resourceId: "MD10MD0010000000000039",
        resourceType: "1",
        resourceSourceId: null,
        resourceUri: "platform.md.message",
        resourceUrl: null,
        resourceDescribe: null,
        parentResourceUri: "platform.md",
        title: "日志消息",
        expand: false,
        checked: false,
        disabled: false,
        path: null,
        name: null,
        icon: null,
        children: [
          {
            resourceId: "MD10MD0010000000000040",
            resourceType: "1",
            resourceSourceId: null,
            resourceUri: "platform.md.message.loggerMgr",
            resourceUrl: null,
            resourceDescribe: null,
            parentResourceUri: "platform.md.message",
            title: "日志管理",
            expand: false,
            checked: false,
            disabled: false,
            path: null,
            name: null,
            icon: null,
            children: [
              {
                resourceId: "MD10MD0010000000000041",
                resourceType: "1",
                resourceSourceId: null,
                resourceUri: "platform.md.message.loggerMgr.businesslog",
                resourceUrl: null,
                resourceDescribe: null,
                parentResourceUri: "platform.md.message.loggerMgr",
                title: "业务日志",
                expand: false,
                checked: false,
                disabled: false,
                path: null,
                name: null,
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
]);
let adata: any = reactive([]);
let data6 = reactive([
  {
    name: "John Brown",
    age: 18,
    address: "New York No. 1 Lake Park",
  },
  {
    name: "Jim Green",
    age: 24,
    address: "London No. 1 Lake Park",
  },
  {
    name: "Joe Black",
    age: 30,
    address: "Sydney No. 1 Lake Park",
  },
  {
    name: "Jon Snow",
    age: 26,
    address: "Ottawa No. 2 Lake Park",
  },
]);
let columns7 = ref([
  {
    title: "Name",
    key: "name",
    render: (h: any, params: any) => {
      return h(
        "div",
        h(
          resolveComponent("AutoComplete"),
          {
            modelValue: data6[params.index].name,
            clearable: true,
            transfer: true,
            filterMethod: function (value: any, option: any) {
              return option.includes(value);
            },
            onChange: (event: any) => {
              data6[params.index].name = event.target._value;
              console.log(data6);
            },
            onClear: (event: any) => {
              data6[params.index].name = event.target._value;
              console.log(data6);
            },
          },
          data4.value.map((item: any) => {
            return h(resolveComponent("Option"), {
              value: item.title,
              onClick: (event: any) => {
                console.log(event);
                data6[params.index].name = event.target.innerHTML;
                console.log(data6);
              },
            });
          })
        )
      );
    },
  },
  {
    title: "Age",
    key: "age",
  },
  {
    title: "Address",
    key: "address",
  },
  {
    title: "Action",
    key: "action",
    width: 150,
    align: "center",
    renderHeader: (h: any, params: any) => {
      return h(
        "div",
        h(
          resolveComponent("Button"),
          {
            type: "primary",
            size: "small",
            style: {
              marginRight: "5px",
            },
            onClick: (event: any) => {
              data6.push({
                name: "",
                age: 26 + params.index++,
                address: `Ottawa No.${params.index} Lake Park`,
              });
            },
          },
          "新增"
        )
      );
    },
    render: (h: any, params: any) => {
      return h("div", [
        h(
          resolveComponent("Button"),
          {
            type: "primary",
            size: "small",
            style: {
              marginRight: "5px",
            },
            onClick: () => {
              show(params.index);
            },
          },
          {
            default() {
              return "View";
            },
          }
        ),
        h(
          resolveComponent("Button"),
          {
            type: "error",
            size: "small",
            onClick: () => {
              remove(params.index);
            },
          },
          {
            default() {
              return "Delete";
            },
          }
        ),
      ]);
    },
  },
]);

const { proxy } = getCurrentInstance() as any;
const aa = (value: any) => {
  console.log(value);
};
const show = (index: any) => {
  proxy.$Modal.info({
    title: "User Info",
    content: `Name：${data6[index].name}<br>Age：${data6[index].age}<br>Address：${data6[index].address}`,
  });
};
const remove = (index: number) => {
  data6.splice(index, 1);
};
</script>
